const Device = require('../models/Device');
const Energy = require('../models/Energy');

// Slab rates for bill calculation
const calculateBill = (units) => {
  let bill = 0;
  if (units <= 100) bill = units * 4.5;
  else if (units <= 300) bill = (100 * 4.5) + (units - 100) * 7.0;
  else bill = (100 * 4.5) + (200 * 7.0) + (units - 300) * 9.5;
  return Math.round(bill);
};

exports.getDashboardData = async (req, res) => {
  try {
    const devices = await Device.find();
    const activeDevices = devices.filter(d => d.status === 'Active' || d.status === 'ON');
    const totalLoad = activeDevices.reduce((sum, d) => sum + (d.watts / 1000), 0);
    const energyLogs = await Energy.find().sort({ timestamp: -1 }).limit(100);
    const totalConsumed = energyLogs.reduce((sum, log) => sum + log.units, 0).toFixed(2);
    const bill = calculateBill(totalConsumed);

    res.json({
      devices,
      metrics: {
        totalConsumed,
        activeDevices: activeDevices.length,
        bill,
        ecoScore: Math.max(70, 100 - (activeDevices.length * 5))
      }
    });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

exports.getDevices = async (req, res) => {
  try {
    const devices = await Device.find();
    res.json(devices);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

exports.toggleDevice = async (req, res) => {
  try {
    const { deviceId, status } = req.body;
    const dev = await Device.findById(deviceId);
    let usage = 0;
    if (status === 'Active' || status === 'ON') {
      usage = dev.watts / 1000;
    }
    const device = await Device.findByIdAndUpdate(deviceId, { status, usage }, { new: true });
    
    // Log for history
    if (status === 'Active' || status === 'ON') {
        await Energy.create({
            deviceName: device.name,
            units: usage * 0.1,
            hoursUsed: 0.1,
            category: device.category
        });
    }

    res.json(device);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

exports.getAnalytics = async (req, res) => {
    try {
        const energyLogs = await Energy.find().sort({ timestamp: -1 }).limit(50);
        const stats = {
            daily: energyLogs.reduce((sum, l) => sum + l.units, 0).toFixed(2),
            weekly: (energyLogs.reduce((sum, l) => sum + l.units, 0) * 5.2).toFixed(2),
            carbon: (energyLogs.reduce((sum, l) => sum + l.units, 0) * 0.82).toFixed(2)
        };
        res.json(stats);
    } catch (err) {
        res.status(500).json({ message: err.message });
    }
};

exports.getBill = async (req, res) => {
    try {
        const logs = await Energy.find();
        const totalUnits = logs.reduce((sum, l) => sum + l.units, 0);
        const bill = calculateBill(totalUnits);
        res.json({ totalUnits, bill, currency: '₹' });
    } catch (err) {
        res.status(500).json({ message: err.message });
    }
};

exports.getAIInsights = async (req, res) => {
    try {
        const devices = await Device.find();
        const active = devices.filter(d => d.status === 'Active');
        const tips = [
            "Neural Pattern: High concurrency detected in HVAC nodes.",
            "Energy usage is 8% below target. Efficiency optimized.",
            "Detected standby load from Gaming PC. Suggesting deep sleep mode.",
            "Peak-hour threshold reached. Avoid heavy washing cycles now."
        ];
        res.json({ insights: tips, activeNodes: active.length });
    } catch (err) {
        res.status(500).json({ message: err.message });
    }
};

exports.getPredictions = async (req, res) => {
  try {
    const devices = await Device.find();
    const currentLoad = devices.filter(d => d.status === 'Active').reduce((sum, d) => sum + (d.watts / 1000), 0);
    const historical = [45, 52, 48, 60, 55, 65, 70];
    const forecast = historical.map(v => Math.round(v + (currentLoad * 10)));
    res.json({ historical, forecast });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

exports.postChat = async (req, res) => {
    try {
        const { query } = req.body;
        // Simple brain simulation
        let response = "I am processing your telemetry query. Neural grid is stable.";
        const q = query.toLowerCase();
        if (q.includes('save')) response = "To reduce your bill, I recommend shifting HVAC usage to 5 AM - 8 AM.";
        else if (q.includes('power')) response = "Your current peak load is generated by the AC and Water Heater.";
        
        res.json({ response });
    } catch (err) {
        res.status(500).json({ message: err.message });
    }
};

exports.addManualEnergy = async (req, res) => {
  try {
    const { deviceName, units, hoursUsed, category } = req.body;
    const newEntry = new Energy({ deviceName, units, hoursUsed, category });
    await newEntry.save();
    res.status(201).json(newEntry);
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
};
